# Chapter 6, Example 1

1. Create a 2D convolutional layer with a single output channel and a 3x3 kernel. The stride is set to 1, and padding is either 'VALID' or 'SAME'.
2. Use a custom weight and bias for the convolutional layer.
3. Apply the convolutional layer to an input tensor, followed by a sigmoid activation function.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

print(torch.__version__)

2.0.1+cu118


In [ ]:
# Input image
I = np.array([[0.5, -0.1, 0.2, 0.3, 0.5],
              [0.8, 0.1, -0.5, 0.5, 0.1],
              [-1.0, 0.2, 0.0, 0.3, -0.2],
              [0.7, 0.1, 0.2, -0.6, 0.3],
              [-0.4, 0.0, 0.2, 0.3, -0.3]]).astype(np.float32)
print(I)

[[ 0.5 -0.1  0.2  0.3  0.5]
 [ 0.8  0.1 -0.5  0.5  0.1]
 [-1.   0.2  0.   0.3 -0.2]
 [ 0.7  0.1  0.2 -0.6  0.3]
 [-0.4  0.   0.2  0.3 -0.3]]


This code is defining an input image represented as a 2D numpy array.

The `np.array` function is used to create a numpy array from a list of lists. Each inner list represents a row of the image, and each element within the inner list represents a pixel in that row.

The `astype(np.float32)` function is used to convert the data type of the elements in the array to `float32`.

The `print(I)` statement is used to print the values of the array to the console, which would give you the following output:



In [ ]:
# Model definition
class MyModel(nn.Module):
    def __init__(self, pad):
        super(MyModel, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3, stride=1, padding=pad)

    def forward(self, x):
        u = self.conv(x)
        y = torch.sigmoid(u)
        return u, y

This code defines a custom PyTorch model named `MyModel` that extends the `nn.Module` base class.

Here's a line-by-line explanation:

- `class MyModel(nn.Module):` This line creates a new class called `MyModel` that inherits from PyTorch's `nn.Module` class. `nn.Module` is a base class for all neural network modules in PyTorch.

- `def __init__(self, pad):` This line defines the constructor for the `MyModel` class. The constructor takes one parameter, `pad`, which specifies the amount of padding to apply in the convolution operation.

- `super(MyModel, self).__init__():` This line calls the constructor of the base `nn.Module` class. This is necessary to properly initialize the base class and make use of its functionalities.

- `self.conv = nn.Conv2d(1, 1, 3, stride=1, padding=pad):` This line creates a 2D convolution layer and assigns it to `self.conv`. The convolution layer takes an input with 1 channel, applies a 3x3 convolutional filter, and produces an output with 1 channel. The stride of the convolution is 1, and the padding is determined by the `pad` parameter.

- `def forward(self, x):` This line defines the `forward` method, which implements the forward pass of the model. The `forward` method takes one parameter, `x`, which is the input data.

- `u = self.conv(x):` This line applies the convolution operation to the input data `x` and assigns the result to `u`.

- `y = torch.sigmoid(u):` This line applies the sigmoid activation function to `u` and assigns the result to `y`.

- `return u, y:` This line returns the outputs of the convolution operation and the activation function.


In [ ]:
# Set filters and bias
w = np.array([[0, 1, 1],[1, 0, 1], [1, 1, 0]]).astype(np.float32).reshape(1,1,3,3)
b = np.array([0.05]).astype(np.float32)

# Valid Padding for Convolution

In [ ]:
# VALID padding for convolution
model = MyModel('valid')

# set weights
model.conv.weight.data = torch.from_numpy(w)
model.conv.bias.data = torch.from_numpy(b)

This code creates an instance of the `MyModel` class and sets the weights and bias for the convolutional layer in the model.

Here's a line-by-line explanation:

- `model = MyModel('valid')`: This line creates an instance of the `MyModel` class with 'valid' padding for the convolution operation.

- `model.conv.weight.data = torch.from_numpy(w)`: This line converts the numpy array `w` to a PyTorch tensor and assigns it to the weight data of the convolutional layer in the model.

- `model.conv.bias.data = torch.from_numpy(b)`: This line does the same as the previous line, but for the bias data.


In [ ]:
# Filters
print(model.conv.weight.data)
# bias
print(model.conv.bias.data)

tensor([[[[0., 1., 1.],
          [1., 0., 1.],
          [1., 1., 0.]]]])
tensor([0.0500])


In [ ]:
# Evaluate u and y
I_out = torch.from_numpy(I.reshape(1, 1, 5, 5))
u, y = model(I_out)

print('VALID padding for convolution\n')
print('u: %s\n'%u.detach().numpy().reshape([3, 3]))
print('y: %s\n'%y.detach().numpy().reshape([3, 3]))

VALID padding for convolution

u: [[-0.34999996  1.3500001   0.75      ]
 [-0.55        0.85        0.05000001]
 [ 0.75        0.05        1.1500001 ]]

y: [[0.41338244 0.79412967 0.6791787 ]
 [0.36586443 0.7005672  0.5124974 ]
 [0.6791787  0.51249737 0.7595109 ]]



This code performs the forward pass of the `MyModel` model with the input image `I`, and then prints the output of the convolution operation and the activation function.

Here's a line-by-line explanation:

- `I_out = torch.from_numpy(I.reshape(1, 1, 5, 5))`: This line converts the numpy array `I` to a PyTorch tensor and reshapes it to have dimensions (1, 1, 5, 5), which corresponds to (batch_size, num_channels, height, width). The reshaped tensor is stored in `I_out`.

- `u, y = model(I_out)`: This line performs the forward pass of the `MyModel` model with `I_out` as the input. The outputs of the convolution operation and the activation function are stored in `u` and `y`, respectively.

- `print('VALID padding for convolution\n')`: This line prints a string to the console.

- `print('u: %s\n'%u.detach().numpy().reshape([3, 3]))`: This line detaches `u` from the computation graph, converts it to a numpy array, reshapes it to have dimensions (3, 3), and then prints it to the console.

- `print('y: %s\n'%y.detach().numpy().reshape([3, 3]))`: This line does the same as the previous print line, but for `y`.


In [ ]:
# Max pooling of square window of size=2, stride=2
pool = nn.MaxPool2d(2, stride=2)
output = pool(y)
print(output)

tensor([[[[0.7941]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


# SAME Padding for Convolution

In [ ]:
# Now try the SAME padding for convolution
model = MyModel('same')

# set weights
model.conv.weight.data = torch.from_numpy(w)
model.conv.bias.data = torch.from_numpy(b)

In [ ]:
# evaluate u and y
I_out = torch.from_numpy(I.reshape(1, 1, 5, 5))
u, y = model(I_out)

# Note that you need to change the reshaping size to print the output properly
print('VALID padding for convolution\n')
print('u: %s\n'%u.detach().numpy().reshape([5, 5]))
print('y: %s\n'%y.detach().numpy().reshape([5, 5]))

VALID padding for convolution

u: [[ 0.75        1.65       -0.15        0.75        0.95000005]
 [-0.45       -0.34999996  1.3500001   0.75        1.1499999 ]
 [ 1.8500001  -0.55        0.85        0.05000001  0.15      ]
 [-1.05        0.75        0.05        1.1500001  -0.75      ]
 [ 0.85        0.15000002 -0.05000001 -0.35000002  0.65000004]]

y: [[0.6791787  0.838891   0.46257016 0.6791787  0.7211152 ]
 [0.38936076 0.41338244 0.79412967 0.6791787  0.7595109 ]
 [0.8641271  0.36586443 0.7005672  0.5124974  0.5374298 ]
 [0.2592251  0.6791787  0.51249737 0.7595109  0.3208213 ]
 [0.7005672  0.5374298  0.48750263 0.4133824  0.6570105 ]]



In [ ]:
# Max pooling of square window of size=2, stride=2
pool = nn.MaxPool2d(2, stride=2)
output = pool(y)
print(output)

tensor([[[[0.8389, 0.7941],
          [0.8641, 0.7595]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)
