# Chapter 8, Example 2

In [2]:
# Import PyTorch
import torch
import torch.nn as nn
import torch.nn.functional as F

# Helper libraries
import numpy as np

# Recurrent Neural Network (RNN) Implementation

In [3]:
class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()

        # Initialize the weights and biases
        self.u = nn.Parameter(torch.tensor([[-1.0, 0.5, 0.2], [0.5, 0.1, -2.0]], dtype=torch.float32))
        self.w = nn.Parameter(torch.tensor([[2.0, 1.3, -1.0]], dtype=torch.float32))
        self.v = nn.Parameter(torch.tensor([[2.0], [-1.5], [0.2]], dtype=torch.float32))
        self.b = nn.Parameter(torch.tensor([0.2, 0.2, 0.2], dtype=torch.float32))
        self.c = nn.Parameter(torch.tensor([0.1], dtype=torch.float32))

    def forward(self, x):
        y = torch.tensor([[0]], dtype=x[0].dtype)

        for i in range(0, len(x)):
            h = torch.tanh(torch.mm(x[i], self.u) + torch.mm(y, self.w) + self.b)
            y = torch.sigmoid(torch.mm(h, self.v) + self.c)

            # Print out the results during iteration
            print(f'h({i + 1}):')
            print(h)
            print(f'y({i + 1}):')
            print(y)
            print(' ')

        return y



The `RNN` class defines a simple recurrent neural network architecture.

## Class Initialization:

1. **Super Initialization**:
    - `super(RNN, self).__init__()`: This initializes the parent `nn.Module` class, which is essential for all PyTorch custom modules.

2. **Weights and Biases Initialization**:
    - `self.u`: Weight matrix for the input `x`.
    - `self.w`: Weight matrix for the previous output `y`.
    - `self.v`: Weight matrix for the hidden state `h`.
    - `self.b`: Bias vector for the hidden state.
    - `self.c`: Bias for the output `y`.

## Forward Method:

This method defines the forward pass of the RNN.

1. **Initial Output (`y`)**:
    - Initialized to a tensor of shape `[1, 1]` with a value of 0. This represents the initial output of the RNN.

2. **Iteration over Input Sequence (`x`)**:
    - For each input in the sequence:
        - Compute the hidden state `h` using the formula:
            \[ h = \tanh(x \times u + y \times w + b) \]
        - Compute the output `y` using the formula:
            \[ y = \sigma(h \times v + c) \]
        - Print the values of `h` and `y` for each iteration.

3. **Return**:
    - The final output `y` is returned.

This RNN implementation showcases the basic recurrent computations where the output from the previous step is used as an input for the current step. The use of the `tanh` activation function for the hidden state and the `sigmoid` activation function for the output is a common choice in many RNN architectures.


In [4]:
x1 = torch.tensor([[1, 2], [-1, 0]], dtype=torch.float32)
x2 = torch.tensor([[-1, 1], [2, -1]], dtype=torch.float32)
x3 = torch.tensor([[0, 3], [3, -1]], dtype=torch.float32)
x = [x1, x2, x3]

In [5]:
rnn = RNN()  # Initialize
y = rnn(x)  # Compute the outputs

h(1):
tensor([[ 0.1974,  0.7163, -0.9985],
        [ 0.8337, -0.2913,  0.0000]], grad_fn=<TanhBackward0>)
y(1):
tensor([[0.3144],
        [0.9006]], grad_fn=<SigmoidBackward0>)
 
h(2):
tensor([[ 0.9812,  0.2058, -0.9807],
        [-0.4611,  0.9789,  0.9353]], grad_fn=<TanhBackward0>)
y(2):
tensor([[0.8260],
        [0.1088]], grad_fn=<SigmoidBackward0>)
 
h(3):
tensor([[ 0.9976,  0.9176, -1.0000],
        [-0.9958,  0.9404,  0.9908]], grad_fn=<TanhBackward0>)
y(3):
tensor([[0.6268],
        [0.0429]], grad_fn=<SigmoidBackward0>)
 
