# Example 3.1

In [1]:
import torch
import numpy as np
import matplotlib.pylab as plt

In [2]:
SEED = 10
np.random.seed(SEED)

## Input data

In [3]:
X = np.array([[0.5, -1.66],[-1.0, -0.51],[0.78, -0.65],[0.04, -0.20]])
print('x:{}'.format(X))

x:[[ 0.5  -1.66]
 [-1.   -0.51]
 [ 0.78 -0.65]
 [ 0.04 -0.2 ]]


## Define a class for a perceptron layer

In [4]:
class PerceptronLayer():
  def __init__(self, no_features, no_labels):
    self.w = torch.tensor(np.random.normal(0., 0.1, (no_features, no_labels)), dtype=torch.double)
    self.b = torch.tensor(0.1*np.random.rand(no_labels), dtype=torch.double)

  def __call__(self, x):
    u = torch.matmul(torch.tensor(x), self.w) + self.b
    y = torch.sigmoid(u)
    return u, y

## Initialize the given layer

In [5]:
model = PerceptronLayer(2, 3)

print('w: {}, b: {}'.format(model.w.numpy(), model.b.numpy()))

w: [[ 0.13315865  0.0715279  -0.15454003]
 [-0.00083838  0.0621336  -0.07200856]], b: [0.01691108 0.00883398 0.06853598]


## Find activations and outputs of the layer

In [6]:
u, y = model(X)

print('u:{}'.format(u.numpy()))
print('y:{}'.format(y.numpy()))

u:[[ 0.08488213 -0.05854384  0.11080017]
 [-0.11581999 -0.09438205  0.25980037]
 [ 0.12131978  0.0242389  -0.00519968]
 [ 0.02240511 -0.00073162  0.07675609]]
y:[[0.5212078  0.48536822 0.52767174]
 [0.47107733 0.47642199 0.56458722]
 [0.5302928  0.50605943 0.49870008]
 [0.50560104 0.49981709 0.51917961]]
